const products = [
  {
    id: 1,
    category:"shirts",
    title: "shirt1",
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    price: "11",
    url: "https://res.cloudinary.com/practice-nodejs-project/image/upload/v1661893233/ecommerce%20react-nodejs/shirt/shirt5_z5dql5.jpg",
  },
  {
    id: 2,
    category:"shirts",
    title: "shirt2",
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    price: "10",
    url: "https://res.cloudinary.com/practice-nodejs-project/image/upload/v1661893233/ecommerce%20react-nodejs/shirt/shirt6_cf12xl.jpg",
  },
  {
    id: 3,
    category:"shirts",
    title: "shirt3",
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    price: "25",
    url: "https://res.cloudinary.com/practice-nodejs-project/image/upload/v1661893233/ecommerce%20react-nodejs/shirt/shirt4_umnsqo.jpg",
  },
  {
    id: 4,
    category:"shirts",
    title: "shirt 4",
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    price: "25",
    url: "https://res.cloudinary.com/practice-nodejs-project/image/upload/v1661893233/ecommerce%20react-nodejs/shirt/shirt3_knsqru.jpg",
  },
  {
    id: 5,
    category:"shirts",
    title: "shirt 5",
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    price: "25",
    url: "https://res.cloudinary.com/practice-nodejs-project/image/upload/v1661893233/ecommerce%20react-nodejs/shirt/shirt2_smsx7a.jpg",
  },
  {
    id: 6,
    category:"shirts",
    title: "shirt 6",
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    price: "25",
    url: "https://res.cloudinary.com/practice-nodejs-project/image/upload/v1661893233/ecommerce%20react-nodejs/shirt/shirt1_bg8tcs.jpg",
  },
  {
    id: 7,
    category:"pants",
    title: "pants 7",
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    price: "25",
    url: "https://res.cloudinary.com/practice-nodejs-project/image/upload/v1661893215/ecommerce%20react-nodejs/pants/pants6_qpapdo.jpg",
  },
  {
    id: 8,
    category:"pants",
    title: "pants 8",
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    price: "25",
    url: "https://res.cloudinary.com/practice-nodejs-project/image/upload/v1661893214/ecommerce%20react-nodejs/pants/pants3_fols3x.jpg",
  },
  {
    id: 9,
    category:"pants",
    title: "pants 9",
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    price: "25",
    url: "https://res.cloudinary.com/practice-nodejs-project/image/upload/v1661893214/ecommerce%20react-nodejs/pants/pants4_f5syts.jpg",
  },
  {
    id: 10,
    category:"pants",
    title: "pants 10",
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    price: "25",
    url: "https://res.cloudinary.com/practice-nodejs-project/image/upload/v1661893214/ecommerce%20react-nodejs/pants/pants5_trr2r9.jpg",
  },
  {
    id: 11,
    category:"pants",
    title: "pants 11",
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    price: "25",
    url: "https://res.cloudinary.com/practice-nodejs-project/image/upload/v1661893214/ecommerce%20react-nodejs/pants/pants5_trr2r9.jpg",
  },
  {
    id: 12,
    category:"pants",
    title: "pants 12",
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    price: "25",
    url: "https://res.cloudinary.com/practice-nodejs-project/image/upload/v1661893213/ecommerce%20react-nodejs/pants/pants1_efx0y9.jpg",
  },
  {
    id: 13,
    category:"shoes",
    title: "shoes 13",
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    price: "25",
    url: "https://res.cloudinary.com/practice-nodejs-project/image/upload/v1661893254/ecommerce%20react-nodejs/shoes/shoes6_fzwpri.jpg",
  },
  {
    id: 14,
    category:"shoes",
    title: "shoes 14",
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    price: "25",
    url: "https://res.cloudinary.com/practice-nodejs-project/image/upload/v1661893252/ecommerce%20react-nodejs/shoes/shoes4_jwogb9.jpg",
  },
  {
    id: 15,
    category:"shoes",
    title: "shoes 15",
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    price: "25",
    url: "https://res.cloudinary.com/practice-nodejs-project/image/upload/v1661893250/ecommerce%20react-nodejs/shoes/shoes3_tj9c8p.jpg",
  },
  {
    id: 16,
    category:"shoes",
    title: "shoes 16",
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    price: "25",
    url: "https://res.cloudinary.com/practice-nodejs-project/image/upload/v1661893250/ecommerce%20react-nodejs/shoes/shoes2_ws9hsa.jpg",
  },
  {
    id: 17,
    category:"shoes",
    title: "shoes 17",
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    price: "25",
    url: "https://res.cloudinary.com/practice-nodejs-project/image/upload/v1661893250/ecommerce%20react-nodejs/shoes/shoes5_uwxjtq.jpg",
  },
  {
    id: 18,
    category:"shoes",
    title: "shoes 18",
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    price: "25",
    url: "https://res.cloudinary.com/practice-nodejs-project/image/upload/v1661893246/ecommerce%20react-nodejs/shoes/shoes1_iowcqq.jpg",
  }, {
    id: 19,
    category:"watch",
    title: "watch 19",
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    price: "25",
    url: "https://res.cloudinary.com/practice-nodejs-project/image/upload/v1661893254/ecommerce%20react-nodejs/watch/watch5_wruclq.jpg",
  },
  {
    id: 20,
    category:"watch",
    title: "watch 20",
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    price: "25",
    url: "https://res.cloudinary.com/practice-nodejs-project/image/upload/v1661893252/ecommerce%20react-nodejs/watch/watch4_gd43ck.jpg",
  },
  {
    id: 21,
    category:"watch",
    title: "watch 21",
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    price: "25",
    url: "https://res.cloudinary.com/practice-nodejs-project/image/upload/v1661893252/ecommerce%20react-nodejs/watch/watch6_vnlgtd.jpg",
  },
  {
    id: 22,
    category:"watch",
    title: "watch 22",
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    price: "25",
    url: "https://res.cloudinary.com/practice-nodejs-project/image/upload/v1661893252/ecommerce%20react-nodejs/watch/watch3_azwvpg.jpg",
  },
  {
    id: 23,
    category:"watch",
    title: "watch 23",
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    price: "25",
    url: "https://res.cloudinary.com/practice-nodejs-project/image/upload/v1661893250/ecommerce%20react-nodejs/watch/watch1_avh4bi.jpg",
  },
  {
    id: 24,
    category:"watch",
    title: "watch 24",
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    price: "25",
    url: "https://res.cloudinary.com/practice-nodejs-project/image/upload/v1661893251/ecommerce%20react-nodejs/watch/watch2_aqzacd.jpg",
  },
];
module.exports = products;
